apiVersion: apps/v1 # Version of the k8s api to use, apps is a group of resources for deployments.
kind: Deployment # This is a deployment resource
metadata: 
  name: mytriotasksql # Name of the deployment
  labels:
    app: mytriotasksql # Labels for the deployment - organisational purposes
spec: 
  replicas: 2 # Desired number of pods
  selector: 
    matchLabels:
      app: mytriotasksql # Specify which pods are controlled by this deployment. looks for tag "nginx" on pods
  strategy: # This specifies the deployment strategy to use and is applied when new version is used
    rollingUpdate: # This is default. Other is recreate (tears down and rebuilds our pods) - rolling update incrementally changes our pods to run the new image
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: # Metadata for the pods
      labels:
        app: mytriotasksql # This is the label assigned to the pods
    spec: 
      containers:
      - name: mytriotasksql
        image: chrisreeves1/mytriotasksql # Image for the container/pods
        env:
          - name: MYSQL_DATABASE
            value: flask-db
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mytriotasksql
spec:
  type: ClusterIP # set the type of Service
  selector:
    app: mytriotasksql # referencing the Pod's label
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306